services:
  frontend:
    image: node:22.9.0
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
    ports:
      - "81:3000"
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=81
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true

  backend:
    image: node:22.9.0
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app:rw
      - /usr/src/app/node_modules
    ports:
      - "82:4000"
    env_file:
      - ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
