name: Continuous Integration Workflow

on:
    workflow_dispatch: 
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]
    
jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./SourceCode

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: "./SourceCode/**/package-lock.json"
                
            - name: Install SourceCode Deps
              run: npm ci
            
            - name: Run Lint
              run: npm run lint
    
    backend-tests:
        needs: lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./SourceCode

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: "./SourceCode/backend/package-lock.json"
            
            - name: Install Backend Deps
              run: npm ci --prefix backend

            - name: Run Vitest with Coverage Metrics (Backend)
              run: npm run test:coverage --prefix backend
            
            - name: Upload Backend Coverage Report
              if: github.actor != 'nektos/act' # Running in GitHub Local Actions
              uses: actions/upload-artifact@v4
              with:
                name: backend-coverage-report
                path: ./SourceCode/backend/coverage/

    frontend-tests:
        needs: lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./SourceCode

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: "./SourceCode/frontend/package-lock.json"
            
            - name: Install Frontend Deps
              run: npm ci --prefix frontend

            - name: Run Vitest with Coverage Metrics (Frontend)
              run: npm run test:coverage --prefix frontend

            - name: Upload Frontend Coverage Report
              if: github.actor != 'nektos/act' # Running in GitHub Local Actions
              uses: actions/upload-artifact@v4
              with:
                name: frontend-coverage-report
                path: ./SourceCode/frontend/coverage/

            - name: Test Placeholder (Frontend)
              run: |
                echo "No Frontend tests to run yet."
                exit 0
