name: Tests (placeholder)

on:
    workflow_dispatch
    # push:
    #     branches: [ main, master ]
    # pull_request:
    #     branches: [ main, master ]

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./SourceCode

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: "./SourceCode/package-lock.json"

            - name: Placeholder
              run: |
                echo "No unit tests to run..."
                echo "Working Dir: ${pwd}"
                exit 0
